# Generated by Django 3.0.7 on 2020-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время написания')),
                ('description', models.CharField(max_length=100, verbose_name='Действие')),
            ],
        ),
    ]
