# Generated by Django 3.0.5 on 2020-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, verbose_name=''),
        ),
    ]
